config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, path_names: {
    sign_up: ''
  }

  root 'landing#home'

  get '/about' => 'landing#about'
  get '/contact' => 'landing#contact'
  get '/gallery' => 'landing#gallery'

  resources :landing

  resources :messages

  resources :books do
    resources :pages
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :pages, dependent: :destroy
  
  validates :name, presence: true

  mount_uploader :avatar, AvatarUploader
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates :name, presence: true
  validates :contact, presence: true
  validates :body, presence: true
end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :book

  validates :name, presence: true

  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @admin = current_admin
    @book = Book.new
    @books = Book.all.sort_by &:created_at
    @messages = Message.all.sort_by &:created_at
  end

  def show
    @book = Book.find(params[:id])
    @page = Page.new
    @pages = @book.pages.sort_by &:created_at
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "book added successfully."
      redirect_to books_path
    else
      flash[:errors] = @book.errors.full_messages.join(". ")
      redirect_to books_path
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "book updated successfully."
      redirect_to books_path
    else
      flash[:errors] = @book.errors.full_messages.join(". ")
      render :edit
    end
  end

  def destroy
    Book.find(params[:id]).destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:name, :avatar, :summary)
  end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  skip_before_action :verify_authenticity_token

  def gallery
    @books = Book.all
  end

  def home
    @admin = current_admin
    @books = Book.all
  end

  def contact
    @message = Message.new
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    @message = Message.new(message_params)
    if @message.save
      # MessageMailer.new_message(@message).deliver_now
      flash[:notice] = "message sent."
    else
      flash[:notice] = "fields cannot be left blank."
    end
    respond_to do |format|
      format.js {render inline: "location.reload();" }
    end
  end

  def destroy
    Message.find(params[:id]).destroy
    flash[:notice] = "message deleted."
    redirect_to books_path
  end

  private

  def message_params
    params.require(:message).permit(:name, :contact, :body)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def show
    @book = Book.find(params[:book_id])
    @page = Page.find(params[:id])

    @pages = @book.pages

    @pagesLength = @pages.length

    @pages.each_with_index do |value, index|
      if @page.id == value.id
        if index == 0
          @nextPage = @pages[1]
        elsif index == (@pagesLength - 1)
          @previousPage = @pages[(index - 1)]
        else
          @nextPage = @pages[index + 1]
          @previousPage = @pages[index - 1]
        end
      end
    end

  end

  def create
    @book = Book.find(params[:book_id])
    @page = Page.new(page_params)
    @page.book = @book

    if @page.save
      flash[:notice] = "page added successfully."
      redirect_to book_path(@book)
    else
      flash[:errors] = @page.errors.full_messages.join(". ")
      redirect_to book_path(@book)
    end
  end

  def destroy
    @book = Book.find(params[:book_id])
    Page.find(params[:id]).destroy
    flash[:notice] = "page removed."
    redirect_to book_path(@book)
  end

  private

  def page_params
    params.require(:page).permit(:name, :avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_book.html.erb
<li class="padding">
  <a href="/books/<%= book.id %>">
  <%= book.name %>
  </a>
  <br/>
  <%= book.summary %>
  <br/>
  <img class="admin-book-display" src="<%= book.avatar.url %>"/>
  <%= button_to "Edit Title / Cover Photo / Summary of Gallery ", edit_book_path(book), :method => "get" %>
  <%= button_to "Delete Gallery", book_path(book), data: {confirm: "Delete Gallery?"}, method: :delete %>
</li>

app/views/books/edit.html.erb
<div class="row" style="min-height: 30em">

<% if admin_signed_in? %>

<div class="padding small-12 columns">

  <div class="small-10 medium-7 small-centered">

    <div class="small-12 small-centered">
    <%= form_for [@book] do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, value: @book.name %>
        </br>
      <%= f.label :body, "Summary" %>
      <%= f.text_area :body, size: "5x5", value: @book.summary %>
        </br>
      <%= f.label :avatar, 'Change Picture' %>
      <%= f.file_field :avatar %>
        </br>
      <%= f.submit "Update Book Info" %>
    <% end %>
    <%= link_to "Back to Book Index", books_path %>
    </div>

  </div>

</div>

<% else %>

  <h3><%= link_to "Home", root_path %></h3>

<% end %>

</div>

app/views/books/index.html.erb
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<div class="row" style="min-height: 30em">

<% if admin_signed_in? %>

<div class="padding small-12 columns">

  <div class="small-10 medium-7 small-centered">

  <h3>Galleries:</h3>

  <section>
    <ol>
      <%= render @books %>
    </ol>
  </section>


  <p><strong>Photo Dimensions:</strong></p>
  <p>7 x 2 for banner photos</p>
  <p>7 x 3 for gallery photos</p>

  <p>
    <%= link_to "Create a New Gallery", '#', :class => "toggler_book" %>
  </p>

  <section class="togglee_book hidden">
    <div class="small-12 small-centered">
    <%= form_for [@book], remote: true do |f| %>
      <%= f.label :name, 'Title' %>
      <%= f.text_field :name %>
        </br>
      <%= f.label :summary, 'Summary' %>
      <%= f.text_area :summary, size: "5x5" %>
        </br>
      <%= f.label :avatar, 'Cover Image' %>
      <%= f.file_field :avatar %>
        </br>
      <%= f.submit "Create Gallery" %>
    <% end %>
    </div>
  </section>

  <br/><br/>

  <h3>Messages:</h3>

  <section>
    <ol>
      <%= render @messages %>
    </ol>
  </section>

  </div>

</div>

<% else %>

<h1>Must be logged in to view content.</h1>

<% end %>

</div>

app/views/books/show.html.erb
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<div class="row">

<div class="small-12 columns padding">

<div class="small-10 small-centered medium-7">

<% if admin_signed_in? %>

<br/>

<div class="pad-top side-padding">
  <h2><%= @book.name %></h2>
  <img class="admin-book-display" src="<%= @book.avatar.url %>"/>
</div>

</br>

<section id="pages-section">
  <ol id="pages" class="side-padding">
    <%= render @pages %>
  </ol>
</section>

</br>

<p>
<%= link_to "Add Page to Book", '#', :class => "toggler_page" %>
</p>

<section class="togglee_page hidden">
  <div class="small-12 small-centered">
    <%= form_for [@book, @page], remote: true do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :avatar, 'Image' %>
      <%= f.file_field :avatar %>
        </br>
      <%= f.hidden_field(:book_id, :value => @book.id) %>
      <%= f.submit "Add Page to Book" %>
    <% end %>
  </div>
</section>

</br>
<h4><%= link_to "Back to Admin Page", books_path %></h4>

<% end %>

</div>

</div>

</div>

app/views/landing/about.html.erb
<div class="row">
  <div class="text-justify" style="height:30em;">
    <div class="small-offset-1 small-10 columns">
      <br/><br/>
      <div class="row">
        <div class="small-12 columns">
          <p class="googlefont2" style="font-size: 130%; text-indent: 40px">
            Patrice and Leslie met at a Tile Design Showroom where they both worked closely with local  builders, architects,  and contractors to design beautiful kitchens and bathrooms for their customers.  In 2014, Leslie and Patrice saw a need and created Miller Stearns Design to fill a void in the design process for new construction, renovation, and remodeling projects.  Patrice and Leslie not only understand the principles of good design but also understand the process of a successful construction project.  Miller Stearns bridges the gap between the buyers' dreams and the builders' requirements.  We help to facilitate an easy and enjoyable experience during a typically stressful process of trying to build a house, also creating a home.
          </p>
        </div>
      </div>
      <br/><br/>
      <hr>
      <br/>
      <div class="row show-for-small-only">
        <div class="small-6 columns">
          <img style="width: 100%;" src="/ryanPic.png">
        </div>
        <div class="small-6 columns">
          <img style="width: 100%;" src="/ryanPic.png">
        </div>
      </div>
      <br/>
      <div class="row">
        <div class="small-12 medium-8 columns">
          <p class="googlefont2" style="font-size: 130%; text-indent: 40px">
            Patrice Miller's career in design began 22 years ago, as a design consultant for Newbridge Homes, Inc, an award winning single-family home builder operating in Massachusetts, Rhode Island and Connecticutt.   While working with Newbridge, Patrice helped many families create the home of their dreams while also honing her skills in project management. These projects helped define Patrice’s passion for design and shaped her exceptional skill of executing a cohesive design throughout an entire home.
          </p>
        </div>
        <div class="hide-for-small-only medium-4 columns">
          <img style="max-height: 14em; float: right;" src="/ryanPic.png">
        </div>
      </div>
      <div class="row hide-for-small-only">
        <br/><br/>
        <hr>
        <br/><br/>
      </div>
      <div class="row">
        <div class="hide-for-small-only medium-4 columns">
          <img style="max-height: 14em;" src="/ryanPic.png">
        </div>
        <div class="small-12 medium-8 columns">
          <p class="googlefont2" style="font-size: 130%; text-indent: 40px">
            Leslie has been in the design industry for over 30 years and holds a degree in graphic design from Skidmore College in Saratoga Springs, NY.  Upon graduation, Leslie worked as a graphic designer, however, after many years she decided she wanted to redirect her focus to interior design.  She prides herself on her versatility and keen eye for design and was easily able to transfer the two-dimensional aspect of design to the three dimension.  After working for several years gaining experience in interior design, Leslie teamed up with Patty Miller to create Miller Stearns Designs.
          </p>
        </div>
      </div>
      <br/>
    </div>
  </div>
</div>

app/views/landing/contact.html.erb
<div class="row">
<div class="medium-12 columns small-centered contact-container">
  <section class="pad-top small-12 medium-6 columns text-center">
    <h3 class="pad-top googlefont1">Patrice Miller</h3>
    <br/>
    <h6>508 922 3460</h6>
    <h6>Patrice@millerstearns.com</h6>
    <h3 class="pad-top googlefont1">Leslie Stearns</h3>
    <br/>
    <h6>508 954 0588</h6>
    <h6>Leslie@millerstearns.com</h6>
  </section>
  <section class="pad-top small-12 medium-6 columns text-center">
    <div class="small-10 small-centered">
    <h4 class="googlefont1 pad-top">Send Us a Message</h4>
    <%= form_for [@message], remote: true do |f| %>
      <%= f.label :name, class: 'text-left googlefont1' %>
      <%= f.text_field :name %>
      <%= f.label :contact, 'Contact Information', class: 'text-left googlefont1' %>
      <%= f.text_field :contact %>
      <%= f.label :body, 'Message', class: 'text-left googlefont1' %>
      <%= f.text_area :body, size: "5x5" %>
      <p class="googlefont1">all fields required *</p>
      <%= f.submit "Send Message", class: 'googlefont1 submit-button' %>
    <% end %>
    </div>
  </section>
</div>
</div>

app/views/landing/gallery.html.erb
<div class="row">
<div class="text-center gallery-container small-12 columns">

  <% if @books.length > 0 %>

    <% @books.each do |book| %>

      <div class="row">

      <h1 class="text-center book-title googlefont1"><%= book.name %></h1>

      <div class="small-offset-1 small-10">

      <% book.pages.each do |page| %>

        <div class="small-12 medium-6 large-4 columns">

          <a href="/books/<%= book.id %>/pages/<%= page.id %>"><img class="gallery-page-display pad-bot" src="<%= page.avatar.url %>"/></a>

        </div>

      <% end %>

      </div>

      </div>

      <br/>

    <% end %>

  <% else %>

    <h1 class="googlefont1">Images Coming Soon.</h1>

  <% end %>

</div>
</div>

app/views/landing/home.html.erb
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<div class="row">
  <div class="small-12 small-centered text-center columns">
    <% if @books.length > 0 %>
      <div class="autoplay no-margin">
        <% @books.each do |book| %>
        <div>
          <img class="cover-image-display" src="<%= book.avatar.url %>"/>
        </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="text-justify" style="height:30em;">
    <div class="small-offset-1 small-10 columns">
      <br/><br/><br/>
      <div class="row">
        <div class="small-12 columns">
          <p class="googlefont2" style="text-indent: 40px; font-size: 150%;">
            Miller Stearns Design is a full-service design firm specializing in residential and commercial interior design.   As designers, our goal is to create beautiful spaces for our clients that are timeless, original and functional.  Our attention to detail and eye for quality helps make our client's visions become a reality.
          </p>
        </div>
      </div>
      <div class="hide-for-small-only">
        <hr>
        <h3 class="text-center googlefont1">timeless&nbsp; ,&nbsp; original&nbsp; ,&nbsp; functional</h3>
        <hr>
      </div>
      <div class="row">
        <div class="small-12 columns">
          <p class="googlefont2" style="text-indent: 40px; font-size: 150%;">
            Miller Stearns has the expertise to handle projects ranging from new construction, renovation and remodels to simply updating an old space with paint and fabric.  From inception to completion, Miller Stearns is determined to create a home that reflects the true personalities of their clients.
          </p>
        </div>
      </div>
      <br/>
    </div>
  </div>
</div>

app/views/landing/index.html.erb
<h1>This page will have a gallery of pictures</h1>

<h3><%= link_to "Home", root_path %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <link rel="stylesheet" type="text/css" href="slick/slick.css"/>
  <link rel="stylesheet" type="text/css" href="slick/slick-theme.css"/>

  <link rel="shortcut icon" type="image/x-icon" href="/millerstearns_tn.jpg" />
  <link href='https://fonts.googleapis.com/css?family=Playfair+Display+SC' rel='stylesheet' type='text/css' />
  <link href='https://fonts.googleapis.com/css?family=Crimson+Text' rel='stylesheet' type='text/css' />

  <title>Miller Stearns Design</title>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="header">
      <a href="/">
      <div class="breaker"></div>
      <div class="breaker"></div>
        <div class="small-12 small-centered columns text-center">
          <img class="text-center padding" id="frontHeaderLogo" src="/millerstearnslogo.jpg"/>
          <h1 class="black googlefont1">Miller&nbsp; Stearns&nbsp; Design</h1>
        </div>
      </a>
    </div>
    <div class="small-12 columns navBar googlefont1">
      <a href="/about">
        <div class="small-4 columns navPiece text-center">
          <p>About<p>
        </div>
      </a>
      <a href="/gallery">
        <div class="small-4 columns navPiece text-center">
          <p>Gallery<p>
        </div>
      </a>
      <a href="/contact">
        <div class="small-4 columns navPiece text-center">
          <p>Contact<p>
        </div>
      </a>
    </div>

    <%- flash.each do |key, value| -%>
      <div class="text-center flash flash-<%= key %>">
        <h5 class="googlefont1"><%= value %></h5>
      </div>
    <%- end -%>

    <br />

    <%= yield %>

    <br />

    <div class="small-12 columns footerBar">
      <div class="small-3 columns footerPiece text-left googlefont1">
        <div class="pad-top">
          <a class="footerLinks" href="/contact">Contact</a>
          <div class="inline text-center">
            <p class="footerContact"><span class="googlefont1">Patrice Miller</span><br/>508 922 3460</p>
          </div>
          <div class="inline text-center" style="padding-left:1.25em;">
            <p class="footerContact"><span class="googlefont1">Leslie Stearns</span><br/>508 954 0588</p>
          </div>
          </p>
        </div>
      </div>
      <div class="small-6 columns footerPiece text-center">
        <div class="pad-top">
          <img class="text-center" id="footerLogo" src="/millerstearnslogo.jpg"/>
          <p class="googlefont1" style="font-size:.6em;">Miller&nbsp; Stearns&nbsp; Design</p>
        </div>
      </div>
      <div class="small-3 columns footerPiece text-right googlefont1">
      <div class="pad-top">
        <% if admin_signed_in? %>
          <%= link_to "Admin", books_path, class: 'footerAdmin' %><br/>
          <%= link_to 'Sign Out', destroy_admin_session_path, method: :delete, class: 'footerAdmin' %>
        <% else %>
          <%= link_to 'Sign In', new_admin_session_path, class: 'footerAdmin' %>
        <% end %>
      </div>
      </div>
    </div>
  </div>

  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <script type="text/javascript" src="slick/slick.min.js"></script>

</body>
</html>

app/views/messages/_message.html.erb
<li class="padding">
  <div>
    <%= message.name %><br/>
    <%= message.created_at.strftime("%I:%M%p on %m/%d/%Y") %><br/>
    <%= message.contact %><br/>
    <%= message.body %>
    <%= button_to "Delete Message", message_path(message), data: {confirm: "Delete this message?"}, method: :delete %>
  </div>
</li>

app/views/pages/_page.html.erb
<li class="padding">
  <div class="page">
    <h3><%= page.name %></h3>
    <img class="admin-page-display" src="<%= page.avatar.url %>"/>
    <%= button_to "Delete Page", book_page_path(@book, page), data: {confirm: "Delete this page?"}, method: :delete %>
  </div>
</li>

app/views/pages/show.html.erb
<div class="row small-12 columns small-centered text-center">

  <div class="small-10 columns small-centered text-center">

    <br/>

    <!-- <h5 class="googlefont1"><%= @page.name %></h5>

    <br/> -->

    <div class="padding">

      <% if @previousPage %>
        <a class="googlefont1 direction-link side-padding" href="/books/<%= @book.id %>/pages/<%= @previousPage.id %>">previous</a>
      <% end %>

      <% if @nextPage %>
        <a class="googlefont1 direction-link side-padding" href="/books/<%= @book.id %>/pages/<%= @nextPage.id %>">next</a>
      <% end %>

    </div>

    <img class="individual-image-display" src="<%= @page.avatar.url %>"/>

    <div class="padding">

      <% if @previousPage %>
        <a class="googlefont1 direction-link side-padding" href="/books/<%= @book.id %>/pages/<%= @previousPage.id %>">previous</a>
      <% end %>

      <% if @nextPage %>
        <a class="googlefont1 direction-link side-padding" href="/books/<%= @book.id %>/pages/<%= @nextPage.id %>">next</a>
      <% end %>

    </div>

    <br/>

  </div>

</div>